version: '3.3'

services:
  mongodb:
    image: mongo
    command: ['--replSet', 'rs0']
    ports:
      - 27017:27017
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'